export const CHANGE_LOGIN_STATUS = "CHANGE_LOGIN_STATUS"
export const SET_USERNAME = "SET_USERNAME"
export const SET_PASSWORD = "SET_PASSWORD"
export const SET_ETHEREUM_ADDRESS = "SET_ETHEREUM_ADDRESS"

export const UPDATE_BALANCES = "UPDATE_BALANCES"
export const RESET_BALANCES = "RESET_BALANCES"

export const ADD_TRANSACTION = "ADD_TRANSACTION"
export const RESET_TRANSACTIONS = "RESET_TRANSACTIONS"